# Generated by Django 3.0.3 on 2020-02-17 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
