# Generated by Django 3.0.2 on 2020-01-22 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts_app', '0002_post_preview_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
