# Generated by Django 3.0.2 on 2020-01-23 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts_app', '0004_auto_20200122_1649'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Ууууу сука, таблица',
        ),
    ]
