# Generated by Django 3.0.3 on 2020-02-18 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users_app.utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0002_auto_20200218_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users_app.utils.get_avatar_upload_path,
                                    verbose_name='Аватар профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                       verbose_name='Пользователь'),
        ),
    ]
