version: "3.7"

networks:
  nginx-django:
    name: nginx-django
    driver: bridge
  django-postgres:
    name: django-postgres
    driver: bridge

volumes:
  static:
    name: static
  postgres_data:
    name: postgres_data
    driver_opts:
      type: none
      o: bind
      device: $PWD/postgres_data

services:
  nginx:
    volumes:
      - static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - ./config.nginx:/etc/nginx/conf.d/default.conf
    restart: always
    container_name: nginx
    image: nginx:1.17-alpine
    ports:
      - 8000:80
    networks:
      - nginx-django
    depends_on:
      - django

  django:
    volumes:
      - static:/app/static
      - ./media:/app/media
      - ./settings.yml:/app/settings.yml
    restart: always
    container_name: django
    image: kolenich/django
    environment:
      - PROJECT_MODE=production
    networks:
      - nginx-django
      - django-postgres
    depends_on:
      - postgres

  postgres:
    restart: always
    container_name: postgres
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nikolay
      - POSTGRES_PASSWORD=Crowel_16
    networks:
      - django-postgres
