version: "3.7"

networks:
  nginx-django:
    name: nginx-django
    driver: bridge
  django-postgres:
    name: django-postgres
    driver: bridge

volumes:
  static:
    name: vlad-static
  nginx-config:
    name: vlad-nginx-config
  postgres_data:
    name: vlad-postgres_data
    driver_opts:
      type: none
      o: bind
      device: $PWD/postgres_data

services:
  nginx:
    volumes:
      - static:/usr/share/nginx/html/static
      - nginx-config:/etc/nginx/conf.d
      - ./media:/usr/share/nginx/html/media
    restart: always
    container_name: vlad-nginx
    image: nginx:1.17-alpine
    ports:
      - 8000:80
    networks:
      - nginx-django
    depends_on:
      - django

  django:
    volumes:
      - static:/app/static
      - nginx-config:/app/nginx
      - ./media:/app/media
    restart: always
    container_name: vlad-django
    image: manstrik/my_forum
    environment:
      - PROJECT_MODE=production
    networks:
      - nginx-django
      - django-postgres
    depends_on:
      - postgres

  postgres:
    restart: always
    container_name: vlad-postgres
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=nikolay
      - POSTGRES_PASSWORD=Crowel_16
    networks:
      - django-postgres
