# Generated by Django 3.0.2 on 2020-01-22 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('summary', models.TextField(verbose_name='Текст на предпросмотре')),
                ('content', models.TextField(verbose_name='Текст поста')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления поста')),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Кто добавил пост')),
            ],
        ),
    ]
