# Generated by Django 3.0.2 on 2020-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_post', models.TextField(default=None, verbose_name='Текст поста')),
            ],
        ),
    ]
