# Generated by Django 3.0.2 on 2020-01-24 08:37

import datetime

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('create_topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpost',
            old_name='new_post',
            new_name='post_text',
        ),
        migrations.AddField(
            model_name='createpost',
            name='post_name',
            field=models.CharField(default=1, max_length=128, verbose_name='Тема поста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createpost',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,
                                       verbose_name='Дата и время поста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createpost',
            name='post_user_name',
            field=models.CharField(default=datetime.datetime(2020, 1, 24, 8, 37, 4, 367795, tzinfo=utc), max_length=128,
                                   verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
