# Generated by Django 3.0.2 on 2020-01-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('create_topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_post', models.TextField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Create_post',
        ),
    ]
