# Generated by Django 3.0.2 on 2020-01-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('create_topic', '0002_auto_20200124_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='post_name',
            field=models.CharField(default='Name', max_length=128, null=True, verbose_name='Тема поста'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='post_user_name',
            field=models.CharField(default='Name_user', max_length=128, verbose_name='Имя пользователя'),
        ),
    ]
