# Generated by Django 3.0.2 on 2020-01-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('create_topic', '0002_auto_20200122_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='new_post',
            field=models.IntegerField(default=None),
        ),
    ]
