# Generated by Django 3.0.2 on 2020-01-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('create_topic', '0003_auto_20200128_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='post_name',
            field=models.CharField(max_length=128, verbose_name='Тема поста'),
        ),
    ]
