# Generated by Django 3.0.2 on 2020-01-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('create_topic', '0004_auto_20200128_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='post_name',
            field=models.CharField(default='Не задано имя поста', max_length=128, verbose_name='Тема поста'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='post_text',
            field=models.TextField(default='Текст не введён', verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='post_user_name',
            field=models.CharField(default='Не задано имя', max_length=128, verbose_name='Имя пользователя'),
        ),
    ]
