# Generated by Django 3.0.2 on 2020-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('create_topic', '0003_auto_20200122_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='new_post',
            field=models.TextField(default=None),
        ),
    ]
