# Generated by Django 3.0.2 on 2020-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('create_topic', '0004_auto_20200122_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='new_post',
            field=models.TextField(default=None, verbose_name='Текст поста'),
        ),
    ]
